### PR TITLE
Fixed compilation with Haxe 3.3

### PR DESCRIPTION
**Pull request by andyli**
Also added a basic TravisCI config.

### CODE REVIEW

**Comment by andyli** [comment]
Thanks! Happy to see you on github again!
How are you lately?
We miss you : )

**Comment by Simn** [comment]
I'm gonna play his manager here: Jason has been very busy with https://todaywelearned.co/ recently and by now his Haxe email folder is filled with hundreds of messages. However, he has long-term plans for Ufront because his business uses it and I can contact him for really urgent stuff.

Also he gave me access to Ufront so I can take care of some small things.

**Comment by andyli** [comment]
Thanks for the info! It's good to know : )

**Comment by andyli** [comment]
One thing, I need admin right for turning on Travis for this repo. Could anyone turn it on for me or maybe it make sense transferring detox to ufront (which I have admin right now)?

**Comment by jasononeil** [comment]
Transferring is a good idea but might involve breaking some links, so I'll save it for another time.  I'll make you an admin for now :)

**Comment by jasononeil** [comment]
Actually, it neede to be in an organisation and Github now supports URL redirects.  So I've swapped it over - does that work?

You may need to update your git remotes next time you pull / push.

**Comment by kevinresol** [comment]
@jasononeil omg....glad too hear from you!

**Comment by kevinresol** [comment]
@simn please check if you have access to all ufront repos. For me, I can only access ufront-mvc.
@jasononeil if you meant to let us maintain the whole ufront repo group, please check on your side too. Thanks.

**Comment by Simn** [comment]
Yes I have full access.

**Comment by kevinresol** [comment]
great!

**Comment by andyli** [comment]
@jasononeil Yes, TravisCI works nicely now. Thanks!

**Pull request merged**
